import { expect, test } from "../fixtures/test";
import { ALL_CHIP } from "../pages/HomePage";
import { toPath } from "../support/url";

/**
 * Regression coverage for the deployed feeds.
 *
 * RSS and the sitemap are generated by a separate request handler from the HTML
 * routes, from the same content directory. That makes them an independent view
 * of the deployed content: if a deploy bakes the wrong content, serves a stale
 * build, or leaks drafts, the feeds disagree with the pages. Each expectation
 * below compares the two views rather than naming any post.
 */

test.describe("GIVEN the deployed RSS feed", () => {
	test("WHEN requesting /rss.xml, THEN it carries exactly the posts the home page lists", async ({
		feedsPage,
		homePage,
	}) => {
		await homePage.goto();
		const cards = await homePage.postCardSummaries();
		const rss = await feedsPage.fetchRss();

		expect(rss.status).toBe(200);
		expect(rss.contentType).toBe("application/rss+xml; charset=utf-8");
		expect(rss.channelTitle).toBe("Raymond Cox");

		await test.step("Then the item set matches the post cards", async () => {
			expect(cards.length).toBeGreaterThan(0);
			expect(rss.items.map((item) => item.title).sort()).toEqual(
				cards.map((card) => card.title).sort(),
			);
		});

		await test.step("Then every item links to a post the home page lists", async () => {
			expect(rss.items.map((item) => toPath(item.link)).sort()).toEqual(
				cards.map((card) => toPath(card.href)).sort(),
			);
		});
	});
});

test.describe("GIVEN the deployed XML sitemap", () => {
	test("WHEN requesting /sitemap.xml, THEN it lists the home page, every post, and one URL per tag chip", async ({
		feedsPage,
		homePage,
	}) => {
		await homePage.goto();
		const cards = await homePage.postCardSummaries();
		const labels = await homePage.tagChipLabels();
		const sitemap = await feedsPage.fetchSitemap();

		expect(sitemap.status).toBe(200);
		expect(sitemap.contentType).toBe("application/xml; charset=utf-8");
		expect(sitemap.raw).toContain(
			'<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
		);

		await test.step("Then the URL set matches what the home page advertises", async () => {
			const expected = [
				"/",
				...cards.map((card) => toPath(card.href)),
				...labels
					.filter((label) => label !== ALL_CHIP)
					.map((label) => `/?tag=${label}`),
			].sort();

			expect(sitemap.locs.map(toPath).sort()).toEqual(expected);
		});
	});

	test("WHEN every advertised URL is requested, THEN each one resolves", async ({
		feedsPage,
	}) => {
		const sitemap = await feedsPage.fetchSitemap();

		expect(sitemap.status).toBe(200);

		for (const loc of sitemap.locs) {
			const path = toPath(loc);
			expect(
				await feedsPage.statusFor(path),
				`expected ${path} to resolve`,
			).toBe(200);
		}
	});
});
